name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  tests:
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        php-version: ['7.4', '8.0', '8.1', '8.2']
    name: Test for PHP Version ${{ matrix.php-version }}
    steps:
      - uses: actions/checkout@v3

      - uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php-version }}

      - uses: php-actions/phpunit@master
        with:
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml
          php_version: ${{ matrix.php-version }}
          version: 9

